name: Closed

on:
  pull_request:
    branches:
    - master
    types: [closed]

jobs:
  closed:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Closed?
      run: echo Closed

    - name: Merged?
      run: echo ${{ github.event.pull_request.merged }}
